services:
    pgs_hash_id.hashids:
        class: Hashids\Hashids
        arguments:
            -
    pgs_hash_id.decorator.router_decorator:
        class: Pgs\HashIdBundle\Decorator\RouterDecorator
        public: false
        decorates: router
        arguments: ["@router.default"]
